// Chris Joakim, Microsoft, 2017/03/31

const express = require('express');
const router  = express.Router();

// The build_timestamp.json file is generated by Grunt
const build_timestamp_obj = require("../build_timestamp.json");

router.get('/', function(req, res) {
  var aname = 'azure-mcpoc';
  var build = build_timestamp_obj['build_timestamp'];
  var date  = new Date();
  var url   = req.protocol + "://" + req.get('host') + req.originalUrl;
  res.render('index', { appname: aname, currdate: date, builddate: build, url: url });
});

module.exports = router;

